schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "rigi_all"
version = "1.5.2"
name = "Rigi-All"
tagline = "Speeds up the Rigify process"
maintainer = "hisanimations <hisprofile029@gmail.com>"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
website = "https://github.com/hisprofile/rigi-all"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Rigging"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]